services:
  api-service:
    build:
      context: ../..
      dockerfile: apps/api-service/Dockerfile
    environment:
      PORT: "8000"
    env_file:
      - ../../.env.compose
      - ../../apps/api-service/.env.local
    volumes:
      - ../../var/keys:/app/var/keys
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  web-app:
    build:
      context: ../..
      dockerfile: apps/web-app/Dockerfile
    environment:
      PORT: "3000"
    env_file:
      - ../../apps/web-app/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api-service
