{{- if not .Values.externalSecrets.enabled -}}
{{- $fullname := include "starter.fullname" . -}}
{{- if .Values.api.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-api" $fullname) .Values.api.secretName }}
  labels:
{{ include "starter.labels" . | indent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
{{- range $key, $value := .Values.api.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
{{- end }}
{{- if .Values.web.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-web" $fullname) .Values.web.secretName }}
  labels:
{{ include "starter.labels" . | indent 4 }}
    app.kubernetes.io/component: web
type: Opaque
data:
{{- range $key, $value := .Values.web.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- if and .Values.worker.enabled .Values.worker.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-worker" $fullname) .Values.worker.secretName }}
  labels:
{{ include "starter.labels" . | indent 4 }}
    app.kubernetes.io/component: worker
type: Opaque
data:
{{- range $key, $value := .Values.worker.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
